// src/data.ts

import type { RootObject } from "./types";

export const db: RootObject = {
  data: {
    id: 192,
    testName: "[PTIT-KS24-Cơ sở dữ liệu] Bài kiểm tra trắc nghiệm cuối môn",
    status: true,
    time: 45,
    type: "TRẮC NGHIỆM",
    created_at: "2026-01-20T14:53:35.000Z",
    questionTests: [
      {
        id: 5167,
        content: "SQL là viết tắt của cụm từ nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20209,
            content: "A. Structured Query Language",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20210,
            content: "B. Strong Question Language",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20211,
            content: "C. Structured Question Layout",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20212,
            content: "D. Standard Query List",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5168,
        content: "Lệnh nào dùng để lấy dữ liệu từ một bảng?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20213,
            content: "A. GET",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20214,
            content: "B. SELECT",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20215,
            content: "C. EXTRACT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20216,
            content: "D. OPEN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5169,
        content: "Câu lệnh nào dùng để tạo một cơ sở dữ liệu mới?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20217,
            content: "A. MAKE DATABASE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20218,
            content: "B. NEW DATABASE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20219,
            content: "C. CREATE DATABASE",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20220,
            content: "D. ADD DATABASE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5170,
        content: "Ràng buộc nào đảm bảo một cột không được để trống?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20221,
            content: "A. UNIQUE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20222,
            content: "B. PRIMARY KEY",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20223,
            content: "C. NOT NULL",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20224,
            content: "D. DEFAULT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5171,
        content:
          "Để xóa toàn bộ bản ghi trong một bảng mà không xóa cấu trúc bảng, ta dùng lệnh?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20225,
            content: "A. REMOVE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20226,
            content: "B. DELETE",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20227,
            content: "C. DROP",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20228,
            content: "D. ERASE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5172,
        content: "Đâu là kiểu dữ liệu dùng để lưu trữ số nguyên trong MySQL?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20229,
            content: "A. VARCHAR",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20230,
            content: "B. INT",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20231,
            content: "C. DATE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20232,
            content: "D. TEXT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5173,
        content: "Mệnh đề nào dùng để sắp xếp kết quả truy vấn?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20233,
            content: "A. GROUP BY",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20234,
            content: "B. SORT BY",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20235,
            content: "C. ORDER BY",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20236,
            content: "D. LIMIT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5174,
        content:
          "Từ khóa nào dùng để lấy các giá trị duy nhất (không trùng lặp)?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20237,
            content: "A. UNIQUE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20238,
            content: "B. DISTINCT",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20239,
            content: "C. DIFFERENT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20240,
            content: "D. ONLY",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5175,
        content: "Để thêm dữ liệu vào bảng, ta sử dụng cặp từ khóa nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20241,
            content: "A. INSERT INTO ... VALUES",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20242,
            content: "B. ADD TO ... VALUES",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20243,
            content: "C. UPDATE ... SET",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20244,
            content: "D. INSERT ... SET",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5176,
        content:
          'Ký tự nào đại diện cho "tất cả các cột" trong câu lệnh SELECT?',
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20245,
            content: "A. #",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20246,
            content: "B. &",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20247,
            content: "C. *",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20248,
            content: "D. @",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5177,
        content: "Mệnh đề WHERE dùng để làm gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20249,
            content: "A. Sắp xếp dữ liệu",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20250,
            content: "B. Nhóm dữ liệu",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20251,
            content: "C. Lọc dữ liệu theo điều kiện",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20252,
            content: "D. Giới hạn số lượng bản ghi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5178,
        content: "Cú pháp DROP TABLE students; thực hiện công việc gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20253,
            content: "A. Xóa toàn bộ dữ liệu trong bảng students",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20254,
            content: "B. Xóa cấu trúc và dữ liệu của bảng students",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20255,
            content: "C. Xóa các hàng có tên là students",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20256,
            content: "D. Ẩn bảng students đi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5179,
        content: "Ý nghĩa của LIMIT 5 trong câu lệnh SQL là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20257,
            content: "A. Lấy 5 cột đầu tiên",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20258,
            content: "B. Lấy dữ liệu từ dòng số 5",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20259,
            content: "C. Chỉ lấy tối đa 5 bản ghi kết quả",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20260,
            content: "D. Bỏ qua 5 bản ghi đầu tiên",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5180,
        content: "Ràng buộc PRIMARY KEY có đặc điểm gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20261,
            content: "A. Cho phép trùng lặp",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20262,
            content: "B. Là duy nhất và không được NULL",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20263,
            content: "C. Cho phép giá trị NULL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20264,
            content: "D. Chỉ dùng được cho kiểu chuỗi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5181,
        content: "MySQL thuộc loại hệ quản trị cơ sở dữ liệu nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20265,
            content: "A. CSDL phân tán",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20266,
            content: "B. CSDL quan hệ (RDBMS)",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20267,
            content: "C. CSDL hướng đối tượng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20268,
            content: "D. CSDL NoSQL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5182,
        content: "Lệnh DESCRIBE table_name; dùng để làm gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20269,
            content: "A. Xem dữ liệu trong bảng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20270,
            content: "B. Xem cấu trúc các cột của bảng",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20271,
            content: "C. Chỉnh sửa bảng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20272,
            content: "D. Xóa bảng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5183,
        content: "Từ khóa DEFAULT dùng để làm gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20273,
            content: "A. Đặt giá trị mặc định cho cột khi không nhập dữ liệu",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20274,
            content: "B. Xóa dữ liệu cũ",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20275,
            content: "C. Kiểm tra tính duy nhất",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20276,
            content: "D. Tự động tăng giá trị",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5184,
        content: "Để sửa đổi cấu trúc bảng (thêm/sửa cột), ta dùng lệnh?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20277,
            content: "A. CHANGE TABLE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20278,
            content: "B. ALTER TABLE",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20279,
            content: "C. MODIFY TABLE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20280,
            content: "D. UPDATE TABLE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5185,
        content: "Mệnh đề nào dùng để chỉ định bảng cần lấy dữ liệu?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20281,
            content: "A. FROM",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20282,
            content: "B. OF",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20283,
            content: "C. IN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20284,
            content: "D. AT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5186,
        content: "Kết quả của SELECT 5 + 10; trong MySQL là?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20285,
            content: 'A. "5+10"',
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20286,
            content: "B. 15",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20287,
            content: "C. Báo lỗi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20288,
            content: "D. 0",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5187,
        content: "Đâu là từ khóa dùng để gán tên tạm (alias) cho cột?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20289,
            content: "A. LIKE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20290,
            content: "B. AS",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20291,
            content: "C. IS",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20292,
            content: "D. TO",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5188,
        content: "Ràng buộc AUTO_INCREMENT thường đi kèm với loại cột nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20293,
            content: "A. VARCHAR",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20294,
            content: "B. PRIMARY KEY (kiểu số)",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20295,
            content: "C. DATE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20296,
            content: "D. FOREIGN KEY",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5189,
        content: "Toán tử BETWEEN dùng để làm gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20297,
            content: "A. Chọn các giá trị trong một khoảng",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20298,
            content: "B. Tìm các chuỗi giống nhau",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20299,
            content: "C. Kết nối hai bảng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20300,
            content: "D. Kiểm tra giá trị NULL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5190,
        content: "Câu lệnh UPDATE students SET age = 20; sẽ làm gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20301,
            content: "A. Thay đổi tuổi của sinh viên đầu tiên thành 20",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20302,
            content: "B. Thay đổi tuổi của tất cả sinh viên thành 20",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20303,
            content: "C. Thêm sinh viên mới 20 tuổi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20304,
            content: "D. Báo lỗi vì thiếu WHERE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5191,
        content: "Từ khóa nào dùng để xóa dữ liệu có điều kiện?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20305,
            content: "A. DELETE FROM ... WHERE",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20306,
            content: "B. REMOVE FROM ... WHERE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20307,
            content: "C. DROP FROM ... WHERE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20308,
            content: "D. UPDATE ... WHERE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5192,
        content: "Trong SQL, ký tự nào dùng để kết thúc một câu lệnh?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20309,
            content: "A. :",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20310,
            content: "B. .",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20311,
            content: "C. ;",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20312,
            content: "D. ,",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5193,
        content: "ASC trong ORDER BY có ý nghĩa gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20313,
            content: "A. Sắp xếp giảm dần",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20314,
            content: "B. Sắp xếp tăng dần",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20315,
            content: "C. Sắp xếp ngẫu nhiên",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20316,
            content: "D. Không sắp xếp",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5194,
        content: "VARCHAR(255) nghĩa là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20317,
            content: "A. Chuỗi có độ dài cố định 255 ký tự",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20318,
            content: "B. Chuỗi có độ dài tối đa 255 ký tự",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20319,
            content: "C. Số có 255 chữ số",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20320,
            content: "D. Mảng gồm 255 phần tử",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5195,
        content: "Câu lệnh CREATE TABLE ... thuộc nhóm lệnh nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20321,
            content: "A. DML",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20322,
            content: "B. DCL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20323,
            content: "C. DDL",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20324,
            content: "D. TCL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5196,
        content: "Lệnh USE database_name; dùng để làm gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 1,
        optionTests: [
          {
            id: 20325,
            content: "A. Tạo CSDL mới",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20326,
            content: "B. Xóa CSDL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20327,
            content: "C. Chọn CSDL làm việc hiện tại",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20328,
            content: "D. Đổi tên CSDL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5197,
        content:
          "Để lấy ra danh sách các sinh viên có tên bắt đầu bằng chữ 'A', ta dùng?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20329,
            content: "A. WHERE name = 'A%'",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20330,
            content: "B. WHERE name LIKE 'A%'",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20331,
            content: "C. WHERE name LIKE '%A'",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20332,
            content: "D. WHERE name IN ('A')",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5198,
        content:
          "Mệnh đề JOIN nào trả về tất cả bản ghi từ bảng bên trái và bản ghi khớp từ bảng bên phải?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20333,
            content: "A. INNER JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20334,
            content: "B. LEFT JOIN",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20335,
            content: "C. RIGHT JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20336,
            content: "D. CROSS JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5199,
        content: "Hàm nào dùng để đếm số lượng bản ghi trong một nhóm?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20337,
            content: "A. SUM()",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20338,
            content: "B. COUNT()",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20339,
            content: "C. TOTAL()",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20340,
            content: "D. AVG()",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5200,
        content: "Mệnh đề HAVING thường được dùng kèm với mệnh đề nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20341,
            content: "A. ORDER BY",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20342,
            content: "B. GROUP BY",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20343,
            content: "C. WHERE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20344,
            content: "D. LIMIT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5201,
        content:
          "Đoạn mã: SELECT SUM(price) FROM products GROUP BY category; thực hiện việc gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20345,
            content: "A. Tính tổng giá của toàn bộ sản phẩm",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20346,
            content: "B. Tính tổng giá sản phẩm cho mỗi danh mục",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20347,
            content: "C. Đếm số sản phẩm mỗi danh mục",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20348,
            content: "D. Tìm giá cao nhất mỗi danh mục",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5202,
        content: "Ràng buộc FOREIGN KEY dùng để làm gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20349,
            content: "A. Đảm bảo dữ liệu không trùng lặp",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20350,
            content: "B. Kết nối hai bảng và đảm bảo tính tham chiếu",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20351,
            content: "C. Tự động tăng giá trị",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20352,
            content: "D. Đặt giá trị mặc định",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5203,
        content: "Đâu là sự khác biệt giữa WHERE và HAVING?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20353,
            content: "A. Không có sự khác biệt",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20354,
            content: "B. WHERE lọc trước khi nhóm, HAVING lọc sau khi nhóm",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20355,
            content: "C. HAVING lọc trước khi nhóm, WHERE lọc sau khi nhóm",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20356,
            content: "D. WHERE chỉ dùng với SELECT, HAVING dùng với UPDATE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5204,
        content:
          "Đoạn mã: SELECT * FROM users LIMIT 10 OFFSET 5; sẽ lấy các bản ghi nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20357,
            content: "A. Từ bản ghi số 1 đến 10",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20358,
            content: "B. Từ bản ghi số 5 đến 15",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20359,
            content: "C. Lấy 10 bản ghi bắt đầu từ sau bản ghi thứ 5",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20360,
            content: "D. Bỏ qua 10 bản ghi đầu và lấy 5 bản ghi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5205,
        content:
          "Mệnh đề JOIN nào chỉ lấy các bản ghi có giá trị khớp nhau ở cả hai bảng?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20361,
            content: "A. FULL JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20362,
            content: "B. INNER JOIN",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20363,
            content: "C. LEFT JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20364,
            content: "D. OUTER JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5206,
        content: "Ý nghĩa của Index (chỉ mục) trong CSDL là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20365,
            content: "A. Giúp tiết kiệm dung lượng bộ nhớ",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20366,
            content: "B. Giúp tăng tốc độ truy vấn dữ liệu",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20367,
            content: "C. Đảm bảo dữ liệu không bị xóa nhầm",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20368,
            content: "D. Làm cho bảng dữ liệu đẹp hơn",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5207,
        content: "VIEW trong CSDL thực tế là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20369,
            content: "A. Một bảng chứa dữ liệu vật lý",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20370,
            content: "B. Một bảng ảo lưu trữ câu lệnh truy vấn",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20371,
            content: "C. Một loại ràng buộc dữ liệu",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20372,
            content: "D. Một bản sao lưu của Database",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5208,
        content: "Lệnh để tạo một Stored Procedure mới là?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20373,
            content: "A. NEW PROCEDURE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20374,
            content: "B. CREATE PROCEDURE",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20375,
            content: "C. CREATE FUNCTION",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20376,
            content: "D. MAKE PROCEDURE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5209,
        content: "Để gọi một Stored Procedure đã tồn tại, ta dùng từ khóa?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20377,
            content: "A. START",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20378,
            content: "B. RUN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20379,
            content: "C. CALL",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20380,
            content: "D. EXECUTE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5210,
        content: "Tham số loại IN trong Stored Procedure có ý nghĩa gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20381,
            content: "A. Là tham số trả giá trị ra ngoài",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20382,
            content: "B. Là tham số truyền giá trị vào procedure",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20383,
            content: "C. Là tham số vừa vào vừa ra",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20384,
            content: "D. Là một biến cục bộ",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5211,
        content:
          "Đoạn mã: SELECT AVG(score) FROM results WHERE student_id = 1; trả về kết quả gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20385,
            content: "A. Tổng điểm của sinh viên 1",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20386,
            content: "B. Điểm trung bình của sinh viên 1",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20387,
            content: "C. Điểm lớn nhất của sinh viên 1",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20388,
            content: "D. Số lượng đầu điểm của sinh viên 1",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5212,
        content:
          "ALTER TABLE students MODIFY email VARCHAR(100) UNIQUE; thực hiện việc gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20389,
            content: "A. Xóa cột email",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20390,
            content: "B. Thêm ràng buộc UNIQUE và đổi độ dài cột email",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20391,
            content: "C. Tạo bảng mới tên là email",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20392,
            content: "D. Cập nhật dữ liệu email cho sinh viên",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5213,
        content:
          "Phép toán SELECT * FROM a CROSS JOIN b; sẽ tạo ra bao nhiêu bản ghi?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20393,
            content: "A. Bằng số dòng bảng a cộng bảng b",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20394,
            content: "B. Bằng số dòng bảng a nhân số dòng bảng b",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20395,
            content: "C. Bằng số dòng bảng a",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20396,
            content: "D. Bằng số dòng bảng b",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5214,
        content: "Điều kiện WHERE price BETWEEN 100 AND 200 tương đương với?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20397,
            content: "A. price > 100 OR price < 200",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20398,
            content: "B. price >= 100 AND price <= 200",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20399,
            content: "C. price > 100 AND price < 200",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20400,
            content: "D. price = 100 AND price = 200",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5215,
        content:
          "UPDATE orders SET status = 'Shipped' WHERE id = 5; kết quả là?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20401,
            content: "A. Đơn hàng số 5 được cập nhật trạng thái",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20402,
            content: "B. Tất cả đơn hàng được cập nhật trạng thái",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20403,
            content: "C. Xóa đơn hàng số 5",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20404,
            content: "D. Thêm đơn hàng mới số 5",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5216,
        content: "Đâu là hàm tổ hợp để tìm giá trị nhỏ nhất?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20405,
            content: "A. SMALL()",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20406,
            content: "B. MIN()",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20407,
            content: "C. LOW()",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20408,
            content: "D. MINIMUM()",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5217,
        content: "Lệnh CREATE INDEX idx_name ON students(fullName); dùng để?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20409,
            content: "A. Tạo cột mới tên là idx_name",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20410,
            content: "B. Tạo chỉ mục trên cột fullName của bảng students",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20411,
            content: "C. Xóa cột fullName",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20412,
            content: "D. Sắp xếp bảng students theo tên",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5218,
        content: "Mệnh đề nào lọc dữ liệu sau khi thực hiện các hàm tổng hợp?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20413,
            content: "A. WHERE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20414,
            content: "B. HAVING",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20415,
            content: "C. GROUP BY",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20416,
            content: "D. ORDER BY",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5219,
        content: "Câu lệnh SELECT count(*) FROM employees; trả về?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20417,
            content: "A. Danh sách nhân viên",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20418,
            content: "B. Tổng số lượng nhân viên",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20419,
            content: "C. Lương trung bình nhân viên",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20420,
            content: "D. Tên của nhân viên đầu tiên",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5220,
        content:
          "Khi thực hiện DELETE FROM table; mà quên WHERE, chuyện gì xảy ra?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20421,
            content: "A. Lệnh bị lỗi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20422,
            content: "B. Toàn bộ dữ liệu trong bảng bị xóa",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20423,
            content: "C. Chỉ dòng đầu tiên bị xóa",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20424,
            content: "D. Hệ thống yêu cầu xác nhận lại",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5221,
        content: "Ràng buộc UNIQUE có tác dụng gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20425,
            content: "A. Cho phép các giá trị giống nhau",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20426,
            content: "B. Đảm bảo tất cả giá trị trong cột là duy nhất",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20427,
            content: "C. Chỉ cho phép nhập số",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20428,
            content: "D. Ngăn chặn giá trị NULL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5222,
        content:
          "Phép JOIN nào lấy bản ghi ở bảng phải kể cả khi không khớp bảng trái?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20429,
            content: "A. LEFT JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20430,
            content: "B. RIGHT JOIN",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20431,
            content: "C. INNER JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20432,
            content: "D. SELF JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5223,
        content: "Lệnh DESC products; viết tắt của?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20433,
            content: "A. DESTROY products",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20434,
            content: "B. DESCRIBE products",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20435,
            content: "C. DESELECT products",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20436,
            content: "D. DISCONNECT products",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5224,
        content: "Toán tử IN trong mệnh đề WHERE dùng để?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20437,
            content: "A. Kiểm tra một giá trị có nằm trong danh sách hay không",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20438,
            content: "B. Tìm kiếm chuỗi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20439,
            content: "C. Tính tổng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20440,
            content: "D. So sánh lớn hơn",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5225,
        content:
          "Câu lệnh: SELECT * FROM table ORDER BY id DESC, name ASC; nghĩa là?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20441,
            content:
              "A. Sắp xếp giảm dần theo id, nếu id trùng thì tăng dần theo name",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20442,
            content: "B. Sắp xếp tăng dần theo id, sau đó giảm dần theo name",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20443,
            content: "C. Chỉ sắp xếp theo id",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20444,
            content: "D. Sắp xếp giảm dần cho cả hai cột",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5226,
        content: "Kiểu dữ liệu TEXT khác gì với VARCHAR?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 2,
        optionTests: [
          {
            id: 20445,
            content: "A. TEXT lưu được dung lượng lớn hơn nhiều so với VARCHAR",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20446,
            content: "B. VARCHAR lưu được nhiều hơn TEXT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20447,
            content: "C. TEXT không chứa được ký tự tiếng Việt",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20448,
            content: "D. Không có sự khác biệt",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5227,
        content: "Truy vấn lồng (Subquery) là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20449,
            content: "A. Một câu lệnh SELECT nằm bên trong câu lệnh SQL khác",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20450,
            content: "B. Một câu lệnh kết nối hai bảng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20451,
            content: "C. Một hàm tự định nghĩa",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20452,
            content: "D. Một loại Trigger",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5228,
        content:
          "Đoạn mã: SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products); trả về?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20453,
            content: "A. Tất cả sản phẩm",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20454,
            content: "B. Các sản phẩm có giá cao hơn giá trung bình",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20455,
            content: "C. Giá trung bình của sản phẩm",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20456,
            content: "D. Báo lỗi vì không thể SELECT lồng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5229,
        content: "Trigger trong SQL là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20457,
            content: "A. Một thủ tục được thực hiện thủ công",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20458,
            content:
              "B. Một đoạn mã tự động thực thi khi có sự kiện (Insert/Update/Delete)",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20459,
            content: "C. Một loại Index đặc biệt",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20460,
            content: "D. Một câu lệnh JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5230,
        content:
          "Transaction trong CSDL có tính chất ACID, chữ A viết tắt của?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20461,
            content: "A. Accuracy",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20462,
            content: "B. Atomicity (Tính nguyên tử)",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20463,
            content: "C. Availability",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20464,
            content: "D. Action",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5231,
        content:
          "Lệnh nào dùng để xác nhận và lưu các thay đổi trong một Transaction?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20465,
            content: "A. SAVE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20466,
            content: "B. ROLLBACK",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20467,
            content: "C. COMMIT",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20468,
            content: "D. END",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5232,
        content:
          "Lệnh nào dùng để hoàn tác các thay đổi khi Transaction gặp lỗi?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20469,
            content: "A. COMMIT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20470,
            content: "B. ROLLBACK",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20471,
            content: "C. REVERT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20472,
            content: "D. DELETE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5233,
        content: "Để xóa một Trigger tên là after_insert_log, ta dùng lệnh?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20473,
            content: "A. DELETE TRIGGER after_insert_log;",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20474,
            content: "B. DROP TRIGGER after_insert_log;",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20475,
            content: "C. REMOVE TRIGGER after_insert_log;",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20476,
            content: "D. CLEAR TRIGGER after_insert_log;",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5234,
        content:
          "Sự khác biệt giữa Subquery tương quan (Correlated Subquery) và Subquery đơn giản là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20477,
            content: "A. Subquery tương quan chạy nhanh hơn",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20478,
            content:
              "B. Subquery tương quan phụ thuộc vào giá trị của truy vấn cha",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20479,
            content: "C. Subquery đơn giản không thể dùng trong WHERE",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20480,
            content: "D. Không có sự khác biệt",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5235,
        content:
          "Đoạn mã: CREATE TRIGGER trg_test BEFORE UPDATE ON orders FOR EACH ROW ... trigger này chạy khi nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20481,
            content: "A. Sau khi cập nhật bảng orders",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20482,
            content: "B. Trước khi cập nhật từng dòng trong bảng orders",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20483,
            content: "C. Khi xóa một đơn hàng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20484,
            content: "D. Khi thêm một đơn hàng mới",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5236,
        content: "Trong Transaction, lệnh START TRANSACTION; có tác dụng gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20485,
            content:
              "A. Tắt chế độ tự động lưu (autocommit) và bắt đầu phiên làm việc mới",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20486,
            content: "B. Lưu dữ liệu ngay lập tức",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20487,
            content: "C. Xóa dữ liệu tạm thời",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20488,
            content: "D. Kết nối đến CSDL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5237,
        content:
          "Khi sử dụng Subquery với toán tử IN, kết quả của subquery trả về phải là?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20489,
            content: "A. Một giá trị duy nhất",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20490,
            content: "B. Một cột (danh sách các giá trị)",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20491,
            content: "C. Toàn bộ các cột trong bảng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20492,
            content: "D. Không trả về gì cả",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5238,
        content: "Ưu điểm lớn nhất của Stored Procedure là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20493,
            content: "A. Giúp code SQL ngắn hơn",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20494,
            content:
              "B. Tăng bảo mật và giảm lưu lượng mạng, tái sử dụng mã lệnh",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20495,
            content: "C. Làm cho DB chạy chậm lại để dễ debug",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20496,
            content: "D. Thay thế hoàn toàn cho View",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5239,
        content:
          "Cú pháp để tạo một View từ một câu lệnh truy vấn phức tạp là?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20497,
            content: "A. MAKE VIEW name AS SELECT...",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20498,
            content: "B. CREATE VIEW name AS SELECT...",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20499,
            content: "C. ADD VIEW name AS SELECT...",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20500,
            content: "D. SAVE VIEW name AS SELECT...",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5240,
        content: "Một Transaction được coi là thành công hoàn toàn khi nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20501,
            content: "A. Khi các câu lệnh INSERT được thực thi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20502,
            content: "B. Khi lệnh COMMIT được gọi thành công",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20503,
            content: "C. Khi người dùng đóng cửa sổ làm việc",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20504,
            content: "D. Khi Database không báo lỗi cú pháp",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5241,
        content:
          "Đoạn mã: SELECT name FROM employees e WHERE EXISTS (SELECT 1 FROM orders o WHERE o.emp_id = e.id); trả về gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20505,
            content: "A. Danh sách nhân viên chưa có đơn hàng nào",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20506,
            content:
              "B. Danh sách nhân viên đã từng thực hiện ít nhất một đơn hàng",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20507,
            content: "C. Tổng số đơn hàng của mỗi nhân viên",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20508,
            content: "D. Lỗi cú pháp SELECT 1",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5242,
        content: "Tại sao không nên lạm dụng Trigger trong thiết kế CSDL?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20509,
            content: "A. Vì nó làm SQL dài hơn",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20510,
            content:
              "B. Vì khó bảo trì, khó debug và có thể làm giảm hiệu năng hệ thống",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20511,
            content: "C. Vì nó tốn tiền mua bản quyền",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20512,
            content: "D. Vì nó không hỗ trợ MySQL",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5243,
        content: "Biến NEW và OLD trong Trigger dùng để làm gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20513,
            content: "A. Chỉ dùng cho sự kiện INSERT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20514,
            content:
              "B. NEW truy cập dữ liệu sau thay đổi, OLD truy cập dữ liệu trước thay đổi",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20515,
            content:
              "C. OLD truy cập dữ liệu sau thay đổi, NEW truy cập dữ liệu trước thay đổi",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20516,
            content: "D. Hai biến này hoàn toàn giống nhau",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5244,
        content: "Tham số OUT trong Stored Procedure có nhiệm vụ gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20517,
            content: "A. Truyền dữ liệu vào trong procedure",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20518,
            content:
              "B. Trả dữ liệu kết quả từ procedure ra ngoài cho người gọi",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20519,
            content: "C. Thoát khỏi procedure ngay lập tức",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20520,
            content: "D. Xóa dữ liệu bên trong procedure",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5245,
        content: "Index giúp tăng tốc độ đọc dữ liệu nhưng nhược điểm là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20521,
            content:
              "A. Làm chậm các thao tác INSERT/UPDATE/DELETE và tốn bộ nhớ",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20522,
            content: "B. Làm dữ liệu bị sai lệch",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20523,
            content: "C. Làm cho SQL khó viết hơn",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20524,
            content: "D. Không có nhược điểm nào",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5246,
        content: "DELIMITER // thường dùng khi nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20525,
            content: "A. Khi thực hiện lệnh SELECT đơn giản",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20526,
            content:
              "B. Khi định nghĩa Stored Procedure hoặc Trigger để thay đổi ký tự kết thúc lệnh",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20527,
            content: "C. Khi muốn xóa Database",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20528,
            content: "D. Khi kết nối đến Server",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5247,
        content: "Truy vấn lồng trong mệnh đề FROM còn được gọi là gì?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20529,
            content: "A. Inline View (Bảng tạm thời)",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20530,
            content: "B. Correlation",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20531,
            content: "C. Procedure",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20532,
            content: "D. Trigger",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5248,
        content: "Câu lệnh ROLLBACK TO savepoint_name; dùng để?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20533,
            content: "A. Hoàn tác toàn bộ Transaction",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20534,
            content: "B. Hoàn tác Transaction về một điểm đã đánh dấu trước đó",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20535,
            content: "C. Xóa Transaction",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20536,
            content: "D. Lưu Transaction",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5249,
        content: 'Lỗi "Subquery returns more than 1 row" xảy ra khi nào?',
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20537,
            content: "A. Khi dùng IN với subquery nhiều dòng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20538,
            content:
              "B. Khi dùng toán tử so sánh bằng (=) với subquery trả về nhiều hơn một dòng",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20539,
            content: "C. Khi dùng LIMIT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20540,
            content: "D. Khi subquery không có dữ liệu",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5250,
        content: "Một View có thể cập nhật dữ liệu (Updatable View) khi nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20541,
            content: "A. Luôn luôn cập nhật được",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20542,
            content:
              "B. Khi View đơn giản, không chứa GROUP BY, JOIN phức tạp hoặc hàm tổng hợp",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20543,
            content: "C. Chỉ khi View chứa lệnh JOIN",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20544,
            content: "D. Không bao giờ cập nhật được",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5251,
        content: "Phép toán UNION khác gì với UNION ALL?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20545,
            content:
              "A. UNION loại bỏ bản ghi trùng lặp, UNION ALL giữ lại tất cả",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20546,
            content:
              "B. UNION ALL loại bỏ bản ghi trùng lặp, UNION giữ lại tất cả",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20547,
            content: "C. UNION chỉ dùng cho số, UNION ALL dùng cho chữ",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20548,
            content: "D. Không có sự khác biệt",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5252,
        content:
          'Trong Transaction, tính chất "Consistency" (Tính nhất quán) đảm bảo điều gì?',
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20549,
            content: "A. Dữ liệu phải được lưu vào ổ cứng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20550,
            content:
              "B. Chuyển CSDL từ trạng thái hợp lệ này sang trạng thái hợp lệ khác",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20551,
            content: "C. Nhiều người dùng có thể truy cập cùng lúc",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20552,
            content: "D. Transaction không thể bị hủy",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5253,
        content:
          "Đoạn mã: SELECT * FROM students WHERE id IN (SELECT student_id FROM attendance); có thể thay thế bằng?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20553,
            content: "A. Phép JOIN giữa bảng students và attendance",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20554,
            content: "B. Phép ORDER BY",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20555,
            content: "C. Phép LIMIT",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20556,
            content: "D. Không thể thay thế",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5254,
        content:
          "Để bảo mật thông tin lương, ta nên dùng đối tượng nào cho người dùng xem?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20557,
            content: "A. Bảng gốc (Table)",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20558,
            content: "B. Một View ẩn đi cột lương",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20559,
            content: "C. Một Trigger",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20560,
            content: "D. Một Transaction",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5255,
        content: "SAVEPOINT my_sp; dùng trong ngữ cảnh nào?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20561,
            content: "A. Khi tạo Procedure",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20562,
            content:
              "B. Đánh dấu một điểm trong Transaction để có thể quay lại",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20563,
            content: "C. Lưu Database ra file",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20564,
            content: "D. Đánh dấu vị trí dòng trong bảng",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
      {
        id: 5256,
        content: "Khi xóa một Stored Procedure, ta dùng lệnh?",
        type: "MỘT LỰA CHỌN",
        status: true,
        point: 4,
        difficulty: 3,
        optionTests: [
          {
            id: 20565,
            content: "A. DELETE PROCEDURE name;",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20566,
            content: "B. DROP PROCEDURE name;",
            isCorrect: true,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20567,
            content: "C. REMOVE PROCEDURE name;",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
          {
            id: 20568,
            content: "D. CLEAR PROCEDURE name;",
            isCorrect: false,
            created_at: "2026-01-20T14:52:45.000Z",
          },
        ],
      },
    ],
  },
};
